# Generated by Django 4.0.6 on 2022-09-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_home', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Ditaile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('room', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('check_in', models.IntegerField()),
                ('check_out', models.IntegerField()),
            ],
        ),
    ]
