# Generated by Django 4.0.6 on 2022-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_home', '0003_hotel_ditaile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_ditaile',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotel_ditaile',
            name='check_out',
            field=models.DateField(),
        ),
    ]
