# Generated by Django 4.0.6 on 2022-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_home', '0004_alter_hotel_ditaile_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_ditaile',
            name='check_in',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel_ditaile',
            name='check_out',
            field=models.DateField(default=''),
        ),
    ]
